resolver: lts-7.12

packages:
- '.'
- location:
    git: git@github.com:SASinestro/indexed-extras.git
    commit: de068934ec9c68a8f2a5e051adafa3369218243e
  extra-dep: true

extra-deps:
- indexed-0.1.3
- rebindable-0.1.2
